services:
  kc_database:
    image: postgres:15
    container_name: kc_database
    environment:
      POSTGRES_DB: ${KEYCLOAK_DATABASE}
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    volumes:
      - kc_database_data:/var/lib/postgresql/data
    networks:
      - authentication-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kc1:
    container_name: kc1
    image: quay.io/keycloak/keycloak:26.0.2
    command:
      - start
      - --hostname-strict=false
      - --proxy-headers=xforwarded
      - --db=postgres
      - --db-url=jdbc:postgresql://kc_database:5432/${KEYCLOAK_DATABASE}
      - --db-username=${KEYCLOAK_DATABASE_USER}
      - --db-password=${KEYCLOAK_DATABASE_PASSWORD}
      - --http-enabled=true
      - --cache=ispn
      - --cache-stack=tcp
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_LOG_LEVEL: INFO
      JGROUPS_DISCOVERY_EXTERNAL_IP: kc1
    ports:
      - "8081:8080"
    depends_on:
      kc_database:
        condition: service_healthy
    networks:
      - authentication-net
      - atlasfreight-net
    restart: unless-stopped

  kc2:
    container_name: kc2
    image: quay.io/keycloak/keycloak:26.0.2
    command:
      - start
      - --hostname-strict=false
      - --proxy-headers=xforwarded
      - --db=postgres
      - --db-url=jdbc:postgresql://kc_database:5432/${KEYCLOAK_DATABASE}
      - --db-username=${KEYCLOAK_DATABASE_USER}
      - --db-password=${KEYCLOAK_DATABASE_PASSWORD}
      - --http-enabled=true
      - --cache=ispn
      - --cache-stack=tcp
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_LOG_LEVEL: INFO
      JGROUPS_DISCOVERY_EXTERNAL_IP: kc2
    ports:
      - "8082:8080"
    depends_on:
      kc_database:
        condition: service_healthy
    networks:
      - authentication-net
      - atlasfreight-net
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: kc-nginx-lb
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kc1
      - kc2
    networks:
      - authentication-net
      - atlasfreight-net
    restart: unless-stopped

volumes:
  kc_database_data:

networks:
  authentication-net:
    driver: bridge
  atlasfreight-net:
    external: true